export const SET_SEARCH_TERM = 'SET_SEARCH_TERM'
export const ADD_MOVIE = 'ADD_MOVIE'
export const EDIT_MOVIE = 'EDIT_MOVIE'
export const DELETE_MOVIE = 'DELETE_MOVIE'
export const ADD_INIT_MOVIES = 'ADD_INIT_MOVIES'
